### ISSUE TITLE
大佬, 动态网关代码求上传

### ISSUE THREAD

**Issue by zhaoqf-cq** [zhaoyibo/spring-cloud-study#11]
大佬, 这个是您的博客地址么? https://windmt.com/2019/01/20/spring-cloud-20-gateway-dynamic-routing/
这是我见过的最好的动态网关博客, 目前没有之一, 可是缺失了一个service, 想学习一下... 大佬您能把代码push上来么?

**Comment by zhaoyibo** [comment]
@qifei0708 感谢支持。
这一块因为在实际使用过程中使用了不少公司内部自研组件，所以源码暂时不方便放。
你说的那个 service，应该是指 GatewayRouteService 吧。这个里边的实现其实就是一些最基本的操作数据库的 CURD 方法，只要理解了数据库里该存什么（可以参考文章后边的「配置格式」），下层服务就很好写了。

**Comment by zhaoqf-cq** [comment]
重点是想学习一下非DB的部分, 可以抛出公司内部组件, 放出来瞅瞅么... 感激不尽
