### ISSUE TITLE
限流没用

### ISSUE THREAD

**Issue by ksgldy** [zhaoyibo/spring-cloud-study#14]
兄台，下载了你的代码，debug模式，RedisRateLimite的 isAllowed都进不去，而且redis啥也存不进去，看了下代码yml种有路由转发，代码中还有，有点懵，浏览器访问后台不管怎样都出Mapping [Exchange: GET http://localhost:10000/fluent/customer/hello/java] to Route{id='fluent_customer_service', uri=lb://CONSUMER, order=0, predicate=Paths: [/fluent/customer/**], match trailing slash: true, gatewayFilters=[[[StripPrefix parts = 2], order = 0], com.windmt.filter.ElapsedFilter@4009668d, [[AddResponseHeader X-Response-Default-Foo = 'Default-Bar'], order = 0]], metadata={}}
不加fluent也不报错，但浏览器报401错误，可能还不会用你的代码

我自己搭的能路由，限流不起作用，也不报错，RedisRateLimite的 isAllowed都进不去，下载了网上的代码，都是这个问题，限流不起作用，debug的话RedisRateLimite的 isAllowed都进不去
盼能解答下

**Comment by zhaoyibo** [comment]
看你的路由信息，是请求到了 `/fluent/customer/**`，这个是没配置限流的。
有限流的是 `/customer/**` 和 `/throttle/customer/**`。
