### ISSUE TITLE
请问gateway配置了hystrix但是并没有触发fallback

### ISSUE THREAD

**Issue by ShawshankLin** [zhaoyibo/spring-cloud-study#2]
https://windmt.com/2018/05/11/spring-cloud-16-spring-cloud-gateway-others/

**Comment by ShawshankLin** [comment]
请问gateway是用ribbon的吗？zuul2是用的ribbon的

**Comment by zhaoyibo** [comment]
gateway 是用的 ribbon，我试了 hystrix 正常呀。
