### ISSUE TITLE
eureka集群启动失败

### ISSUE THREAD

**Issue by MatthewLeeOnTheWay** [zhaoyibo/spring-cloud-study#4]
你好，我是从spring cloud 1.x迁移过来的，eureka server集群模式迁移到2.x版本失败了。在您的源码这里启动eureka集群也是碰到一样的问题==Failed to initialize DiscoveryClient

**Comment by zhaoyibo** [comment]
1.x 升级到 2.x 注意下依赖和配置。我源码里的 eureka server 试过可以启动。
