### ISSUE TITLE
spring cloud gateway 限流未生效

### ISSUE THREAD

**Issue by zlyam13** [zhaoyibo/spring-cloud-study#8]
获取了您的代码,本地跑了一下gateway 相关代码,自己压了一下,发现限流未生效,,不知道为何

**Comment by yiminyangguang520** [comment]
@zlyam13 亲测限流可用呀，试试http://localhost:10000/customer/hello/test?token=1212

**Comment by zlyam13** [comment]
不好意思,生效了,貌似配置是针对单个路由的,有没有针对全局限流的呢?

**Comment by zhaoyibo** [comment]
@zlyam13 全局限流可以用 GlobalFilter 来实现
